
import React, { useState, useEffect } from 'react';
import { Routes, Route, useNavigate, useLocation, Navigate } from 'react-router-dom';
import { PageType } from './components/Header';
import { Hero } from './components/Hero';
import { MattressBuilder } from './components/MattressBuilder';
import { ServicePage } from './components/ServicePage';
import { BrandStory } from './components/BrandStory';
import { ProductShop } from './components/ProductShop';
import { BlogPage } from './components/BlogPage';
import { AdminPage } from './components/AdminPage';
import { AIConsultantModal } from './components/AIConsultantModal';
import { ShoppingCartModal } from './components/ShoppingCartModal';
import { PassportPage } from './components/PassportPage';
import { LoginModal } from './components/LoginModal';
import { PolicyPage, PolicyTab } from './components/PolicyPage';
import { AIRecommendation, CartItem, UserProfile, SiteSettings } from './types';
import { dataService } from './services/dataService';
import { SEO } from './components/SEO';
import { MainLayout } from './components/layouts/MainLayout';

// Toast Component
const Toast = ({ message, icon, visible, onClose }: { message: string, icon: React.ReactNode, visible: boolean, onClose: () => void }) => {
    useEffect(() => {
        if (visible) {
            const timer = setTimeout(onClose, 3000);
            return () => clearTimeout(timer);
        }
    }, [visible, onClose]);

    if (!visible) return null;

    return (
        <div className="fixed bottom-24 lg:bottom-10 left-1/2 transform -translate-x-1/2 z-[100] pointer-events-none animate-fade-in-up">
            <div className="bg-[#3E4E88]/90 backdrop-blur-md text-white px-6 py-3 rounded-full shadow-xl border-2 border-white/50 flex items-center gap-3 min-w-max">
                <div className="text-ac-yellow text-xl filter drop-shadow-sm">
                    {icon}
                </div>
                <p className="font-bold text-sm tracking-wide">{message}</p>
            </div>
        </div>
    );
};

function App() {
  const navigate = useNavigate();
  const location = useLocation();
  
  // Determine current page type from URL for Header active state
  const getPageType = (path: string): PageType => {
      if (path === '/' || path === '/home') return 'home';
      if (path.startsWith('/shop')) return 'shop';
      if (path.startsWith('/builder')) return 'builder';
      if (path.startsWith('/blog')) return 'blog';
      if (path.startsWith('/service') || path.startsWith('/store')) return 'service'; 
      if (path.startsWith('/story')) return 'story';
      if (path.startsWith('/passport')) return 'passport';
      if (path.startsWith('/policy')) return 'policy';
      if (path.startsWith('/admin')) return 'admin';
      return 'home';
  };

  const currentPage = getPageType(location.pathname);

  const [showAiModal, setShowAiModal] = useState(false);
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [aiRecommendation, setAiRecommendation] = useState<AIRecommendation | null>(null);
  const [policyTab, setPolicyTab] = useState<PolicyTab>('privacy');
  
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  const [isCartOpen, setIsCartOpen] = useState(false);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
  const [isMusicPlaying, setIsMusicPlaying] = useState(true);
  const [siteSettings, setSiteSettings] = useState<SiteSettings>({
      announcementText: '',
      announcementColor: '#F4A261',
      showAnnouncement: false,
      heroImage: '',
      storyImage1: '',
      storyImage2: '',
      gtmId: '',
      googleSiteVerificationId: '',
      blogAutoGenerateInterval: 'off',
      lastBlogAutoGenerateDate: '',
      enableBalloon: false,
      balloonCode: '',
      balloonDesc: ''
  });
  const [toast, setToast] = useState<{ visible: boolean, message: string, icon: React.ReactNode }>({
      visible: false, message: '', icon: null
  });

  // Launch State for Initial Transition
  const [isLaunch, setIsLaunch] = useState(true);

  useEffect(() => {
    // Disable launch mode after initial animation window (2.5s)
    const timer = setTimeout(() => setIsLaunch(false), 2500);
    return () => clearTimeout(timer);
  }, []);

  // Load Data
  useEffect(() => {
    setCartItems(dataService.getCart());
    setUserProfile(dataService.getUserProfile());
    
    const loadSettings = async () => {
      const settings = await dataService.getSiteSettings();
      setSiteSettings(settings);
    };
    loadSettings();

    handleUnlockAchievement('new_resident');
  }, []);

  // Scroll to top on route change
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  // Navigation Handler
  const handleNavigate = (page: PageType) => {
      switch (page) {
          case 'home': navigate('/'); break;
          case 'shop': navigate('/shop'); break;
          case 'builder': navigate('/builder'); break;
          case 'blog': navigate('/blog'); break;
          case 'store': navigate('/service'); break; 
          case 'service': navigate('/service'); break;
          case 'story': navigate('/story'); break;
          case 'admin': navigate('/admin'); break;
          case 'passport': navigate('/passport'); break;
          case 'policy': navigate('/policy'); break;
          default: navigate('/');
      }
  };

  // AI Handlers
  const handleAiApply = (rec: AIRecommendation) => {
    setAiRecommendation(rec);
    navigate('/builder');
    setShowAiModal(false);
  };

  const handleConfigApplied = () => {
    setAiRecommendation(null);
  };

  // Cart Handlers
  const addToCart = (item: CartItem) => {
    const updatedCart = [...cartItems, item];
    setCartItems(updatedCart);
    dataService.saveCart(updatedCart);
    setIsCartOpen(true);
    const total = updatedCart.reduce((sum, i) => sum + i.price * i.quantity, 0);
    if (total >= 50000) handleUnlockAchievement('wealthy');
  };

  const removeFromCart = (id: string) => {
    const updatedCart = cartItems.filter(item => item.id !== id);
    setCartItems(updatedCart);
    dataService.saveCart(updatedCart);
  };

  // Gamification
  const handleUnlockAchievement = (id: string) => {
      const achievement = dataService.unlockAchievement(id);
      if (achievement) {
          setToast({
              visible: true,
              message: `成就解鎖：${achievement.name}`,
              icon: <span className="text-xl">{achievement.icon}</span>
          });
          setUserProfile(dataService.getUserProfile());
      }
  };

  const handleUpdateProfile = (p: UserProfile) => {
      setUserProfile(p);
  };

  const handleToggleMusic = () => {
    setIsMusicPlaying(!isMusicPlaying);
  };

  const handleOpenPassport = () => {
      if (userProfile && userProfile.name === '島民代表') {
          setShowLoginModal(true);
      } else {
          navigate('/passport');
      }
  };

  const handleLogin = (name: string, islandName: string) => {
      if (userProfile) {
          const updatedProfile = { ...userProfile, name, islandName };
          dataService.saveUserProfile(updatedProfile);
          setUserProfile(updatedProfile);
          setShowLoginModal(false);
          navigate('/passport');
      }
  };

  const handleOpenPolicy = (tab: PolicyTab) => {
      setPolicyTab(tab);
      navigate('/policy');
  };

  return (
    <>
      <SEO /> 
      
      <Toast 
        visible={toast.visible} 
        message={toast.message} 
        icon={toast.icon} 
        onClose={() => setToast(prev => ({...prev, visible: false}))} 
      />

      {/* Modals */}
      {showAiModal && (
        <AIConsultantModal 
          onClose={() => setShowAiModal(false)}
          onApplyConfig={handleAiApply}
        />
      )}
      <ShoppingCartModal 
        isOpen={isCartOpen}
        onClose={() => setIsCartOpen(false)}
        cartItems={cartItems}
        onRemoveItem={removeFromCart}
      />
      {showLoginModal && (
          <LoginModal 
            onLogin={handleLogin}
            onClose={() => setShowLoginModal(false)}
          />
      )}

      <Routes>
          {/* Admin Routes */}
          <Route path="/admin/*" element={<AdminPage />} />

          {/* Main App Layout Routes */}
          <Route element={
            <MainLayout 
                currentPage={currentPage}
                onNavigate={handleNavigate}
                cartCount={cartItems.length}
                onOpenCart={() => setIsCartOpen(true)}
                userProfile={userProfile || {name:'Guest',islandName:'Heim',title:'',avatar:'😊',miles:0,unlockedStamps:[],lastCheckIn:''}}
                isMusicPlaying={isMusicPlaying}
                onToggleMusic={handleToggleMusic}
                onOpenPassport={handleOpenPassport}
                onAskAi={() => setShowAiModal(true)}
                siteSettings={siteSettings}
                onOpenPolicy={handleOpenPolicy}
                isLaunch={isLaunch}
            />
          }>
              <Route path="/" element={
                  <>
                    <Hero 
                      onStartCustomizing={() => navigate('/builder')} 
                      onAskAi={() => setShowAiModal(true)}
                      siteSettings={siteSettings}
                    />
                    <section className="py-12 px-6">
                       <div className="max-w-4xl mx-auto bg-ac-orange rounded-[3rem] p-8 md:p-12 text-center text-white shadow-[0_10px_0_#d68c55] relative overflow-hidden">
                          <div className="relative z-10">
                              <h2 className="text-3xl md:text-4xl font-black mb-4 leading-tight">
                                現在就加入
                                <br className="md:hidden" />
                                無人島移居計畫！
                              </h2>
                              <p className="mb-8 text-lg font-medium opacity-90">首購還贈送「限定版葉子圖案枕頭」DIY 方程式喔！</p>
                              <button 
                                onClick={() => navigate('/builder')}
                                className="bg-white text-ac-orange px-8 py-4 rounded-full font-black text-xl shadow-lg hover:scale-105 transition-transform"
                              >
                                立刻出發
                              </button>
                          </div>
                          <div className="absolute -right-10 -bottom-20 w-64 h-64 bg-white/20 rounded-full"></div>
                          <div className="absolute -left-10 -top-20 w-64 h-64 bg-white/20 rounded-full"></div>
                       </div>
                    </section>
                  </>
              } />
              {/* REMOVED pt-20 lg:pt-24 from all routes below to fix spacing issue */}
              <Route path="/builder" element={
                  <div className="animate-fade-in-up">
                    <MattressBuilder 
                      onOpenAiModal={() => setShowAiModal(true)}
                      aiConfig={aiRecommendation}
                      onConfigApplied={handleConfigApplied}
                      onAddToCart={addToCart}
                      onUnlockAchievement={handleUnlockAchievement}
                    />
                  </div>
              } />
              <Route path="/shop" element={
                  <div className="animate-fade-in-up">
                    <ProductShop 
                        onAddToCart={addToCart} 
                        onUnlockAchievement={handleUnlockAchievement}
                    />
                  </div>
              } />
              <Route path="/blog" element={
                  <div className="animate-fade-in-up">
                    <BlogPage 
                        onNavigate={handleNavigate} 
                        onUnlockAchievement={handleUnlockAchievement}
                    />
                  </div>
              } />
              <Route path="/passport" element={
                  userProfile ? (
                    <div className="animate-fade-in-up">
                        <SEO title="島民護照" description="查看您的海姆島護照、累積哩數與解鎖成就。" />
                        <PassportPage 
                            userProfile={userProfile}
                            onUpdateProfile={handleUpdateProfile}
                        />
                    </div>
                  ) : <Navigate to="/" />
              } />
              <Route path="/policy" element={
                  <div className="animate-fade-in-up">
                    <SEO title="服務條款與隱私權" description="海姆名床的服務條款、隱私權政策與退換貨說明。" />
                    <PolicyPage activeTab={policyTab} onTabChange={setPolicyTab} />
                  </div>
              } />
              <Route path="/service" element={<div className="animate-fade-in-up"><ServicePage siteSettings={siteSettings} /></div>} />
              <Route path="/store" element={<Navigate to="/service" replace />} />
              <Route path="/story" element={
                  <div className="animate-fade-in-up">
                      <SEO title="品牌故事" description="關於海姆名床的起源，以及哈姆店長在無人島的睡眠方程式。" />
                      <BrandStory siteSettings={siteSettings} />
                  </div>
              } />
              
              {/* Catch all */}
              <Route path="*" element={<Navigate to="/" replace />} />
          </Route>
      </Routes>
    </>
  );
}

export default App;
