
export enum MaterialType {
  COVER = 'COVER',
  COMFORT_LAYER = 'COMFORT_LAYER',
  SUPPORT_LAYER = 'SUPPORT_LAYER',
}

export interface Material {
  id: string;
  name: string;
  type: MaterialType;
  price: number; // Fixed add-on price
  description: string;
  color: string; // Tailwind class or hex
  thickness: number; // cm
  benefits: string[];
  stats?: { // Decision support data
      firmness: number; // 1 (Soft) to 5 (Hard)
      breathability: number; // 1 (Low) to 5 (High)
  };
}

export interface Size {
  id: string;
  name: string;
  width: number;
  length: number;
  basePrice: number; // Price difference relative to standard size (+/-)
}

export interface MattressConfig {
  sizeId: string;
  coverId: string;
  comfortLayerIds: string[]; // Array for multi-select
  supportLayerId: string;
}

export interface AIRecommendation {
  reasoning: string;
  config: Partial<MattressConfig>;
  suggestedPillowId?: string; // ID of a recommended pillow product
}

export interface ProductReview {
  author: string;
  rating: number;
  content: string;
  date: string;
  helpfulCount?: number; // New
  tags?: string[]; // New: e.g. "已購入標準雙人", "睡過回不去"
}

export interface ProductSEO {
    title: string;
    description: string;
    keywords: string[];
}

export interface ProductVariant {
  id: string; // e.g., 'single_xl', 'double'
  name: string; // e.g., '3.5尺'
  price: number;
}

export interface Product {
  id: string;
  name: string;
  category: 'Limited' | 'Pillow' | 'Home' | 'Accessory';
  price: number; // Base price or default display price
  variants?: ProductVariant[]; // Optional variants for size pricing
  description: string; // Short description for list
  fullDescription: string; // Long description for detail
  imagePrompt: string; // Main image prompt
  uploadedImage?: string; // Base64 string for uploaded image (High priority)
  galleryPrompts: string[]; // Additional images
  tags: ('NEW' | 'SALE' | 'HOT' | 'LIMITED')[];
  kocName?: string;
  features: { icon: string; label: string }[];
  specs: { label: string; value: string }[];
  reviews: ProductReview[];
  seo?: ProductSEO;
}

export interface BlogPost {
  id: string;
  title: string;
  date: string;
  excerpt: string;
  category: string;
  imagePrompt: string;
  content: string; // HTML content
  tags: string[];
  author: string;
  relatedLink?: {
    label: string;
    page: 'builder' | 'shop' | 'store' | 'home' | 'story';
  };
}

export interface CartItem {
  id: string;
  type: 'product' | 'custom';
  name: string;
  price: number;
  quantity: number;
  productId?: string; // For standard products
  variant?: { id: string; name: string }; // For product variants
  // For custom mattresses
  config?: MattressConfig;
  configSummary?: string; // e.g. "標準雙人 | 雲朵表布 | 乳膠+記憶棉 | 獨立筒"
}

// Gamification Types
export interface Stamp {
  id: string;
  name: string;
  description: string;
  milesReward: number;
  icon: string; // Emoji or Icon name
}

export interface UserProfile {
  name: string;
  islandName: string;
  title: string;
  avatar: string; // Emoji
  miles: number;
  unlockedStamps: string[]; // IDs of unlocked stamps
  lastCheckIn: string; // Date string YYYY-MM-DD
}

// HeimOS 3.0 Types
export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export interface Order {
  id: string;
  customerName: string; // From UserProfile or 'Guest'
  items: CartItem[];
  totalAmount: number;
  status: OrderStatus;
  date: string;
}

export interface FaqItem {
  id: string;
  category: string;
  question: string;
  answer: string;
}

export interface SiteSettings {
  announcementText: string;
  announcementColor: string; // Tailwind bg class or hex
  showAnnouncement: boolean;
  heroImage?: string; // Base64 string for custom Hero image
  storyImage1?: string; // Base64 string for Brand Story image 1
  storyImage2?: string; // Base64 string for Brand Story image 2
  
  // SEO & Analytics
  googleSiteVerificationId?: string; // For Google Search Console meta tag
  gtmId?: string; // Google Tag Manager ID (GTM-XXXXX)

  // AI Automation
  blogAutoGenerateInterval?: 'off' | 'daily' | 'weekly';
  lastBlogAutoGenerateDate?: string; // ISO Date String

  // Random Events
  enableBalloon?: boolean;
  balloonCode?: string; // e.g., "HAMU2024"
  balloonDesc?: string; // e.g., "結帳輸入現折 $500"
}

export type PageType = 'home' | 'builder' | 'story' | 'store' | 'shop' | 'blog' | 'admin' | 'passport' | 'policy';
