
import React, { useState, useEffect } from 'react';
import { Icons } from './Icons';
import { dataService } from '../services/dataService';
import { generateAIBlogPost, generateProductSEO, generateAIImage, generateProductDescription, generateHeimStyleImage } from '../services/geminiService';
import { Product, BlogPost, Order, OrderStatus, UserProfile, SiteSettings, FaqItem, Material, Size, MaterialType } from '../types';
import { AIImage } from './AIImage';

type AdminTab = 'dashboard' | 'orders' | 'products' | 'blog' | 'residents' | 'faq' | 'settings' | 'workshop' | 'converter';

export const AdminPage: React.FC = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [password, setPassword] = useState('');
  const [activeTab, setActiveTab] = useState<AdminTab>('dashboard');
  const [isSidebarOpen, setSidebarOpen] = useState(false);
  
  // Data State
  const [products, setProducts] = useState<Product[]>([]);
  const [blogPosts, setBlogPosts] = useState<BlogPost[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);
  const [users, setUsers] = useState<UserProfile[]>([]);
  const [faqs, setFaqs] = useState<FaqItem[]>([]);
  const [materials, setMaterials] = useState<Material[]>([]);
  const [sizes, setSizes] = useState<Size[]>([]);
  const [settings, setSettings] = useState<SiteSettings>({ 
      announcementText: '', announcementColor: '', showAnnouncement: false, heroImage: '', storyImage1: '', storyImage2: '', gtmId: '', googleSiteVerificationId: '', blogAutoGenerateInterval: 'off', lastBlogAutoGenerateDate: '', enableBalloon: false, balloonCode: '', balloonDesc: ''
  });
  
  // Refresh Data
  const refreshData = async () => {
    const [p, b, o, f, m, s, st] = await Promise.all([
        dataService.getProducts(),
        dataService.getBlogPosts(),
        dataService.getOrders(),
        dataService.getFAQs(),
        dataService.getMaterials(),
        dataService.getSizes(),
        dataService.getSiteSettings()
    ]);
    
    setProducts(p);
    setBlogPosts(b);
    setOrders(o);
    setUsers(dataService.getAllProfiles());
    setFaqs(f);
    setMaterials(m);
    setSizes(s);
    setSettings(st);
  };

  useEffect(() => {
    if (isLoggedIn) refreshData();
  }, [isLoggedIn]);

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (password === 'hamu888') {
      setIsLoggedIn(true);
    } else {
      alert('密碼錯誤是也！');
    }
  };

  const handleNavClick = (tab: AdminTab) => {
    setActiveTab(tab);
    setSidebarOpen(false);
  }

  if (!isLoggedIn) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-ac-green/80 pt-20">
        <div className="bg-[#F2F9F5] p-8 rounded-3xl shadow-2xl max-w-md w-full border-4 border-white text-center">
          <h2 className="text-2xl font-black text-ac-darkBrown mb-6 mt-4">海姆實業 (Heim Inc.)</h2>
          <p className="text-ac-brown mb-4 font-bold">HeimOS 3.0 管理系統</p>
          <form onSubmit={handleLogin}>
            <input 
              type="password" 
              placeholder="請輸入通行碼 (hamu888)"
              className="w-full p-3 rounded-xl border-2 border-gray-300 mb-4 text-center font-bold text-base outline-none focus:border-ac-green"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <button type="submit" className="w-full bg-ac-green text-white font-black py-3 rounded-xl shadow-md hover:bg-[#66a04b] transition-colors">
              登入
            </button>
          </form>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#F2F9F5] flex flex-col lg:flex-row">
        {/* Mobile Header for Admin */}
        <div className="lg:hidden fixed top-0 left-0 right-0 bg-ac-darkBrown text-white p-4 flex items-center justify-between z-40 border-b-4 border-white shadow-md h-16">
            <div className="flex items-center">
                <div className="w-8 h-8 bg-ac-green rounded-full flex items-center justify-center text-lg mr-2 border-2 border-white">🐹</div>
                <div className="font-black">HeimOS 3.0</div>
            </div>
            <button onClick={() => setSidebarOpen(!isSidebarOpen)} className="p-2 bg-white/10 rounded-lg">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
            </button>
        </div>

        {/* SIDEBAR */}
        <aside className={`fixed lg:sticky top-0 h-full w-64 bg-ac-darkBrown text-[#F2F9F5] flex flex-col z-50 border-r-4 border-white transform transition-transform duration-300 ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}`}>
            <div className="p-6 border-b border-white/10 flex items-center h-24 lg:h-auto">
                <div className="w-10 h-10 bg-ac-green rounded-full flex items-center justify-center text-xl mr-3 border-2 border-white">🐹</div>
                <div>
                    <h3 className="font-black">哈姆店長</h3>
                    <p className="text-xs text-ac-green font-bold">Administrator</p>
                </div>
                <button onClick={() => setSidebarOpen(false)} className="lg:hidden ml-auto text-white/50 hover:text-white">
                     <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                </button>
            </div>
            <nav className="flex-1 p-4 space-y-2 overflow-y-auto">
                {[
                    { id: 'dashboard', label: '營運儀表板', icon: <Icons.Dashboard className="w-5 h-5"/> },
                    { id: 'orders', label: '訂單管理', icon: <Icons.ClipboardList className="w-5 h-5"/> },
                    { id: 'products', label: '商品中心', icon: <Icons.BellBag className="w-5 h-5"/> },
                    { id: 'workshop', label: '工坊管理', icon: <Icons.Workbench className="w-5 h-5"/> },
                    { id: 'converter', label: '風格轉換', icon: <Icons.Palette className="w-5 h-5"/> },
                    { id: 'blog', label: '日誌中心', icon: <Icons.Dodo className="w-5 h-5"/> },
                    { id: 'faq', label: '常見問題', icon: <span className="w-5 h-5 flex items-center justify-center font-bold">?</span> },
                    { id: 'residents', label: '島民名冊', icon: <Icons.Users className="w-5 h-5"/> },
                    { id: 'settings', label: '系統設定', icon: <Icons.Settings className="w-5 h-5"/> },
                ].map(item => (
                    <button
                        key={item.id}
                        onClick={() => handleNavClick(item.id as AdminTab)}
                        className={`w-full flex items-center p-3 rounded-xl font-bold transition-all ${activeTab === item.id ? 'bg-ac-green text-white shadow-md translate-x-1' : 'text-gray-300 hover:bg-white/10'}`}
                    >
                        {item.icon} <span className="ml-3">{item.label}</span>
                    </button>
                ))}
            </nav>
            <div className="p-4 border-t border-white/10">
                <button onClick={() => setIsLoggedIn(false)} className="w-full flex items-center justify-center p-2 text-red-300 font-bold hover:bg-red-900/20 rounded-xl">
                    <Icons.Lock className="w-4 h-4 mr-2"/> 登出
                </button>
            </div>
        </aside>

        {/* Overlay for mobile sidebar */}
        {isSidebarOpen && <div className="fixed inset-0 bg-black/50 z-40 lg:hidden" onClick={() => setSidebarOpen(false)}></div>}

        {/* MAIN CONTENT */}
        <main className="flex-1 p-4 pt-20 lg:p-8 lg:pt-12 min-w-0">
            <h1 className="text-2xl lg:text-3xl font-black text-ac-darkBrown mb-8 flex items-center">
                {activeTab === 'dashboard' && '營運儀表板'}
                {activeTab === 'orders' && '訂單追蹤系統'}
                {activeTab === 'products' && '商品管理中心'}
                {activeTab === 'workshop' && '工坊管理系統 (Workshop)'}
                {activeTab === 'converter' && '風格深度轉換器 (Banana Pro)'}
                {activeTab === 'blog' && '內容行銷中心'}
                {activeTab === 'faq' && '常見問題集 (FAQ)'}
                {activeTab === 'residents' && '島民 CRM'}
                {activeTab === 'settings' && '全站系統設定'}
            </h1>

            <div className="animate-fade-in-up">
                {activeTab === 'dashboard' && <DashboardTab products={products} posts={blogPosts} orders={orders} users={users} />}
                {activeTab === 'orders' && <OrdersTab orders={orders} refresh={refreshData} />}
                {activeTab === 'products' && <ProductsTab products={products} refresh={refreshData} />}
                {activeTab === 'workshop' && <WorkshopTab materials={materials} sizes={sizes} refresh={refreshData} />}
                {activeTab === 'converter' && <StyleTransferTab />}
                {activeTab === 'blog' && <BlogTab posts={blogPosts} refresh={refreshData} settings={settings} />}
                {activeTab === 'faq' && <FaqTab faqs={faqs} refresh={refreshData} />}
                {activeTab === 'residents' && <ResidentsTab users={users} />}
                {activeTab === 'settings' && <SettingsTab settings={settings} refresh={refreshData} />}
            </div>
        </main>
    </div>
  );
};

// --- Sub Components ---

const StyleTransferTab = () => {
    const [sourceImage, setSourceImage] = useState<string | null>(null);
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [prompt, setPrompt] = useState('An isometric view of a cozy bedroom with wooden furniture.');
    const [isGenerating, setIsGenerating] = useState(false);

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            const reader = new FileReader();
            reader.onload = () => setSourceImage(reader.result as string);
            reader.readAsDataURL(file);
        }
    };

    const handleGenerate = async () => {
        if (!prompt) return alert('請輸入描述文字');
        setIsGenerating(true);
        try {
            const result = await generateHeimStyleImage(sourceImage, prompt);
            setGeneratedImage(result);
        } catch (error) {
            console.error(error);
            alert('轉換失敗，請確認 API Key 或稍後再試。');
        } finally {
            setIsGenerating(false);
        }
    };

    const handleDownload = () => {
        if (generatedImage) {
            const link = document.createElement('a');
            link.href = generatedImage;
            link.download = `heim-style-${Date.now()}.png`;
            link.click();
        }
    };

    return (
        <div className="bg-white rounded-2xl shadow-sm p-8">
            <div className="bg-ac-cream p-6 rounded-xl border-l-8 border-ac-green mb-8">
                <h3 className="text-xl font-black text-ac-darkBrown mb-2">風格深度轉換器 (Banana Pro)</h3>
                <p className="text-ac-brown font-medium">
                    利用 Gemini 3 Pro 模型，將您上傳的照片深度重構成「海姆島」風格。
                    <br/>亦可僅輸入文字進行生成。
                </p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Left: Input */}
                <div className="space-y-6">
                    <div className="bg-gray-50 p-4 rounded-2xl border-2 border-dashed border-gray-300 text-center">
                        <input 
                            type="file" 
                            accept="image/*" 
                            onChange={handleImageUpload}
                            className="hidden"
                            id="style-upload"
                        />
                        <label htmlFor="style-upload" className="cursor-pointer block h-full w-full min-h-[200px] flex flex-col items-center justify-center text-gray-400 hover:text-ac-green transition-colors">
                            {sourceImage ? (
                                <img src={sourceImage} alt="Source" className="max-h-[300px] object-contain rounded-lg shadow-sm" />
                            ) : (
                                <>
                                    <Icons.Image className="w-12 h-12 mb-2" />
                                    <span className="font-bold">點擊上傳參考圖片 (可選)</span>
                                </>
                            )}
                        </label>
                        {sourceImage && (
                            <button onClick={() => setSourceImage(null)} className="mt-2 text-red-400 text-xs font-bold hover:underline">清除圖片</button>
                        )}
                    </div>

                    <div>
                        <label className="block text-sm font-bold text-ac-brown mb-2">場景描述 (Prompt)</label>
                        <textarea 
                            className="w-full border-2 border-ac-cream rounded-xl p-4 h-32 focus:border-ac-green outline-none text-ac-darkBrown font-medium"
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            placeholder="描述您想要轉換的場景細節..."
                        />
                    </div>

                    <button 
                        onClick={handleGenerate}
                        disabled={isGenerating}
                        className={`w-full py-4 rounded-xl font-black text-lg shadow-md transition-all flex items-center justify-center
                            ${isGenerating ? 'bg-gray-300 text-white cursor-not-allowed' : 'bg-ac-green text-white hover:bg-[#66a04b] hover:translate-y-[-2px]'}
                        `}
                    >
                        {isGenerating ? (
                            <>
                                <Icons.Sparkles className="w-6 h-6 mr-2 animate-spin" />
                                魔法施展中...
                            </>
                        ) : (
                            <>
                                <Icons.Palette className="w-6 h-6 mr-2" />
                                開始轉換
                            </>
                        )}
                    </button>
                </div>

                {/* Right: Output */}
                <div className="bg-[#FDFBF7] rounded-2xl border-4 border-ac-cream p-6 flex flex-col items-center justify-center relative min-h-[400px]">
                    <div className="absolute top-4 left-4 bg-ac-yellow text-ac-darkBrown text-xs font-black px-2 py-1 rounded shadow-sm">
                        PREVIEW
                    </div>
                    
                    {generatedImage ? (
                        <div className="w-full h-full flex flex-col items-center">
                            <img src={generatedImage} alt="Generated" className="w-full h-auto rounded-xl shadow-lg mb-6 animate-pop" />
                            <button 
                                onClick={handleDownload}
                                className="bg-ac-blue text-white px-6 py-2 rounded-full font-bold shadow-md hover:bg-blue-500 transition-colors"
                            >
                                下載圖片
                            </button>
                        </div>
                    ) : (
                        <div className="text-center opacity-40">
                            <div className="w-24 h-24 bg-ac-cream rounded-full flex items-center justify-center mx-auto mb-4">
                                <Icons.Sparkles className="w-12 h-12 text-ac-brown" />
                            </div>
                            <p className="font-bold text-ac-brown">生成的圖片將顯示於此</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

const DashboardTab = ({ products, posts, orders, users }: { products: Product[], posts: BlogPost[], orders: Order[], users: UserProfile[] }) => (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <div className="bg-white p-6 rounded-2xl shadow-sm border-l-8 border-ac-green flex flex-col">
            <h4 className="text-ac-brown font-bold mb-2">總營收 (模擬)</h4>
            <p className="text-4xl font-black text-ac-darkBrown mt-auto">
                {(orders.reduce((sum, o) => sum + o.totalAmount, 0)).toLocaleString()}
            </p>
        </div>
        <div className="bg-white p-6 rounded-2xl shadow-sm border-l-8 border-ac-orange">
            <h4 className="text-ac-brown font-bold mb-2">待處理訂單</h4>
            <p className="text-4xl font-black text-ac-darkBrown mt-auto">
                {orders.filter(o => o.status === OrderStatus.PENDING).length}
            </p>
        </div>
        <div className="bg-white p-6 rounded-2xl shadow-sm border-l-8 border-ac-blue">
            <h4 className="text-ac-brown font-bold mb-2">移居島民</h4>
            <p className="text-4xl font-black text-ac-darkBrown mt-auto">{users.length}</p>
        </div>
        <div className="bg-white p-6 rounded-2xl shadow-sm border-l-8 border-yellow-400">
            <h4 className="text-ac-brown font-bold mb-2">內容數量</h4>
            <p className="text-xl font-bold text-ac-darkBrown mt-auto">
                {products.length} 商品 / {posts.length} 日誌
            </p>
        </div>
        
        <div className="col-span-full bg-white rounded-2xl p-8 shadow-sm border-4 border-ac-cream">
            <h3 className="text-xl font-bold text-ac-darkBrown mb-4">HeimOS 3.3 更新</h3>
            <div className="bg-ac-cream p-4 rounded-xl text-ac-brown border-l-4 border-ac-orange">
                <p>新增風格深度轉換器 (Banana Pro)！讓您輕鬆將照片重構成海姆島風格是也！</p>
            </div>
        </div>
    </div>
);

const ResidentsTab = ({ users }: { users: UserProfile[] }) => {
    return (
        <div className="bg-white rounded-2xl shadow-sm p-6">
            <div className="overflow-x-auto">
                <table className="w-full text-left">
                    <thead>
                        <tr className="text-ac-brown text-sm border-b-2 border-ac-cream">
                            <th className="pb-3 pl-2">頭像</th>
                            <th className="pb-3">姓名</th>
                            <th className="pb-3">稱號</th>
                            <th className="pb-3">島嶼</th>
                            <th className="pb-3">哩數</th>
                            <th className="pb-3">最後簽到</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-ac-cream">
                        {users.map((user, idx) => (
                            <tr key={idx} className="hover:bg-gray-50">
                                <td className="py-4 pl-2 text-2xl">{user.avatar}</td>
                                <td className="py-4 font-bold text-ac-darkBrown">{user.name}</td>
                                <td className="py-4 text-sm text-ac-brown">{user.title}</td>
                                <td className="py-4 font-bold text-ac-green">{user.islandName}</td>
                                <td className="py-4 font-bold text-ac-blue">{user.miles.toLocaleString()}</td>
                                <td className="py-4 text-xs text-gray-500">{user.lastCheckIn || '尚未簽到'}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

// ... SizeEditor, MaterialEditor, WorkshopTab, OrdersTab, FaqTab, ProductEditor, BlogEditor, ProductsTab, BlogTab remain similar ...
const SizeEditor = ({ size, onClose, onSave }: { size: Size | null, onClose: () => void, onSave: (s: Size) => void }) => {
    const [formData, setFormData] = useState<Size>(size || { id: '', name: '', width: 0, length: 0, basePrice: 10000 });
    const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); if (!formData.id) { alert('請輸入 ID'); return; } onSave(formData); };
    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div><label className="block text-xs font-bold text-ac-green mb-1">ID</label><input required className="border p-2 rounded w-full" value={formData.id} onChange={e => setFormData({...formData, id: e.target.value})} disabled={!!size?.id && size.id !== ''} /></div>
            <div><label className="block text-xs font-bold text-ac-green mb-1">名稱</label><input required className="border p-2 rounded w-full" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} /></div>
            <div className="grid grid-cols-2 gap-4">
                <div><label className="block text-xs font-bold text-ac-green mb-1">寬度 (cm)</label><input required type="number" className="border p-2 rounded w-full" value={formData.width} onChange={e => setFormData({...formData, width: Number(e.target.value)})} /></div>
                <div><label className="block text-xs font-bold text-ac-green mb-1">長度 (cm)</label><input required type="number" className="border p-2 rounded w-full" value={formData.length} onChange={e => setFormData({...formData, length: Number(e.target.value)})} /></div>
            </div>
            <div>
                <label className="block text-xs font-bold text-ac-green mb-1">價差 (Price Diff)</label>
                <input required type="number" className="border p-2 rounded w-full" value={formData.basePrice} onChange={e => setFormData({...formData, basePrice: Number(e.target.value)})} />
                <p className="text-xs text-gray-400 mt-1">
                    相對於標準雙人(5尺)的價格差異。<br/>
                    例如：標準雙人填 0，單人加大填 -3000，雙人加大填 3000。
                </p>
            </div>
            <div className="flex justify-end gap-2 mt-4"><button type="button" onClick={onClose} className="px-4 py-2 text-gray-500 font-bold">取消</button><button type="submit" className="bg-ac-green text-white px-6 py-2 rounded-lg font-bold">儲存</button></div>
        </form>
    );
};

const MaterialEditor = ({ material, onClose, onSave }: { material: Material | null, onClose: () => void, onSave: (m: Material) => void }) => {
    const [formData, setFormData] = useState<Material>(material || { id: '', name: '', type: MaterialType.COVER, price: 0, description: '', color: '', thickness: 0, benefits: [], stats: { firmness: 3, breathability: 3 } });
    const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); onSave(formData); };
    return (
        <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <div><label className="block text-xs font-bold text-ac-green mb-1">ID</label><input required className="border p-2 rounded w-full" value={formData.id} onChange={e => setFormData({...formData, id: e.target.value})} /></div>
                <div><label className="block text-xs font-bold text-ac-green mb-1">類型</label><select className="border p-2 rounded w-full" value={formData.type} onChange={e => setFormData({...formData, type: e.target.value as MaterialType})}><option value={MaterialType.COVER}>表布</option><option value={MaterialType.COMFORT_LAYER}>舒適層</option><option value={MaterialType.SUPPORT_LAYER}>支撐層</option></select></div>
            </div>
            <div><label className="block text-xs font-bold text-ac-green mb-1">名稱</label><input required className="border p-2 rounded w-full" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} /></div>
            <div><label className="block text-xs font-bold text-ac-green mb-1">描述</label><textarea required className="border p-2 rounded w-full h-20" value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} /></div>
            <div className="grid grid-cols-2 gap-4">
                <div><label className="block text-xs font-bold text-ac-green mb-1">加購價 (Fixed Price)</label><input required type="number" className="border p-2 rounded w-full" value={formData.price} onChange={e => setFormData({...formData, price: Number(e.target.value)})} /></div>
                <div><label className="block text-xs font-bold text-ac-green mb-1">厚度 (cm)</label><input required type="number" className="border p-2 rounded w-full" value={formData.thickness} onChange={e => setFormData({...formData, thickness: Number(e.target.value)})} /></div>
            </div>
            <div><label className="block text-xs font-bold text-ac-green mb-1">顏色 (Hex/Tailwind)</label><input required className="border p-2 rounded w-full" value={formData.color} onChange={e => setFormData({...formData, color: e.target.value})} /></div>
            <div className="flex justify-end gap-2 mt-4"><button type="button" onClick={onClose} className="px-4 py-2 text-gray-500 font-bold">取消</button><button type="submit" className="bg-ac-green text-white px-6 py-2 rounded-lg font-bold">儲存</button></div>
        </form>
    );
};

const WorkshopTab = ({ materials, sizes, refresh }: { materials: Material[], sizes: Size[], refresh: () => void }) => {
    const [editSize, setEditSize] = useState<Size | null>(null);
    const [editMaterial, setEditMaterial] = useState<Material | null>(null);
    const [materialTab, setMaterialTab] = useState<MaterialType>(MaterialType.COVER);
    
    const handleSaveSize = async (size: Size) => { await dataService.saveSize(size); refresh(); setEditSize(null); };
    const handleDeleteSize = async (id: string) => { if (confirm('Del?')) { await dataService.deleteSize(id); refresh(); } };
    const handleSaveMaterial = async (material: Material) => { await dataService.saveMaterial(material); refresh(); setEditMaterial(null); };
    const handleDeleteMaterial = async (id: string) => { if (confirm('Del?')) { await dataService.deleteMaterial(id); refresh(); } };

    if (editSize) return <div className="bg-white rounded-2xl shadow-sm p-6"><h3 className="text-xl font-bold mb-6">編輯尺寸</h3><SizeEditor size={editSize} onClose={() => setEditSize(null)} onSave={handleSaveSize} /></div>;
    if (editMaterial) return <div className="bg-white rounded-2xl shadow-sm p-6"><h3 className="text-xl font-bold mb-6">編輯材質</h3><MaterialEditor material={editMaterial} onClose={() => setEditMaterial(null)} onSave={handleSaveMaterial} /></div>;

    const filteredMaterials = materials.filter(m => m.type === materialTab);
    return (
        <div className="space-y-8">
            <div className="bg-white rounded-2xl shadow-sm p-6">
                <div className="flex justify-between items-center mb-6"><h3 className="text-xl font-bold">尺寸</h3><button onClick={() => setEditSize({ id: '', name: '', width: 0, length: 0, basePrice: 0 })} className="bg-ac-green text-white px-3 py-1 rounded font-bold">新增</button></div>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-4">{sizes.map(s => <div key={s.id} className="border p-2 rounded hover:border-ac-blue cursor-pointer" onClick={() => setEditSize(s)}>{s.name} ({s.basePrice > 0 ? `+${s.basePrice}` : s.basePrice})</div>)}</div>
            </div>
            <div className="bg-white rounded-2xl shadow-sm p-6">
                 <div className="flex justify-between items-center mb-6"><h3 className="text-xl font-bold">材質</h3><button onClick={() => setEditMaterial({ id: '', name: '', type: materialTab, price: 0, description: '', color: 'bg-gray-200', thickness: 0, benefits: [], stats: { firmness: 3, breathability: 3 } })} className="bg-ac-green text-white px-3 py-1 rounded font-bold">新增</button></div>
                 <div className="flex gap-2 mb-4 overflow-x-auto pb-2">{[{id:MaterialType.COVER, label:'表布'},{id:MaterialType.COMFORT_LAYER, label:'舒適'},{id:MaterialType.SUPPORT_LAYER, label:'支撐'}].map(t => <button key={t.id} onClick={() => setMaterialTab(t.id)} className={`px-3 py-1 rounded whitespace-nowrap ${materialTab===t.id?'bg-ac-green text-white':'bg-gray-100'}`}>{t.label}</button>)}</div>
                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{filteredMaterials.map(m => <div key={m.id} className="border p-2 rounded hover:border-ac-blue cursor-pointer flex gap-2" onClick={() => setEditMaterial(m)}><div className={`w-10 h-10 flex-shrink-0 ${m.color.startsWith('#')?'':m.color}`} style={m.color.startsWith('#')?{backgroundColor:m.color}:{}}></div><div className="truncate font-bold flex-1">{m.name} (+${m.price})</div></div>)}</div>
            </div>
        </div>
    );
};

const OrdersTab = ({ orders, refresh }: { orders: Order[], refresh: () => void }) => {
    const handleStatusChange = async (id: string, status: OrderStatus) => { await dataService.updateOrderStatus(id, status); refresh(); };
    return <div className="bg-white rounded-2xl shadow-sm p-6 overflow-x-auto"><div className="min-w-[600px]">{orders.map(o => <div key={o.id} className="border-b py-2 flex justify-between items-center"><div><span className="font-bold">{o.customerName}</span> <span className="text-sm text-gray-500">${o.totalAmount}</span></div><select value={o.status} onChange={e => handleStatusChange(o.id, e.target.value as OrderStatus)} className="border rounded p-1 text-sm"><option value="PENDING">待處理</option><option value="PROCESSING">處理中</option><option value="COMPLETED">完成</option></select></div>)}</div></div>
};

const FaqTab = ({ faqs, refresh }: { faqs: FaqItem[], refresh: () => void }) => {
    return <div className="bg-white p-6 rounded-2xl"><h3 className="font-bold mb-4">FAQ Editor</h3><p>功能開發中...</p></div>
};

const SettingsTab = ({ settings, refresh }: { settings: SiteSettings, refresh: () => void }) => {
    const [formData, setFormData] = useState(settings);
    
    const handleChange = (field: keyof SiteSettings, value: any) => {
        setFormData(prev => ({ ...prev, [field]: value }));
    };

    const handleSave = async () => {
        await dataService.saveSiteSettings(formData);
        refresh();
        alert('設定已儲存！');
    };

    return (
        <div className="bg-white p-6 rounded-2xl space-y-8">
            {/* Announcement */}
            <div>
                <h3 className="font-bold mb-4 text-lg text-ac-darkBrown border-b pb-2">全站公告</h3>
                <div className="space-y-4">
                    <label className="flex items-center gap-2 cursor-pointer">
                        <input type="checkbox" checked={formData.showAnnouncement} onChange={e => handleChange('showAnnouncement', e.target.checked)} className="w-5 h-5 text-ac-green" />
                        <span className="font-bold">啟用全站公告</span>
                    </label>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 mb-1">公告內容</label>
                        <input className="border p-2 rounded w-full" value={formData.announcementText} onChange={e => handleChange('announcementText', e.target.value)} />
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 mb-1">背景顏色 (Hex)</label>
                        <input type="color" className="border p-1 rounded h-10 w-full" value={formData.announcementColor} onChange={e => handleChange('announcementColor', e.target.value)} />
                    </div>
                </div>
            </div>

            {/* Balloon Event */}
            <div>
                <h3 className="font-bold mb-4 text-lg text-ac-darkBrown border-b pb-2">氣球活動設定 (Balloon Event)</h3>
                <div className="space-y-4">
                    <label className="flex items-center gap-2 cursor-pointer">
                        <input type="checkbox" checked={formData.enableBalloon} onChange={e => handleChange('enableBalloon', e.target.checked)} className="w-5 h-5 text-ac-green" />
                        <span className="font-bold">啟用氣球飄過活動</span>
                    </label>
                    <div className="grid md:grid-cols-2 gap-4">
                        <div>
                            <label className="block text-xs font-bold text-gray-500 mb-1">隱藏優惠碼</label>
                            <input className="border p-2 rounded w-full" value={formData.balloonCode || ''} onChange={e => handleChange('balloonCode', e.target.value)} placeholder="例如：HAMU2024" />
                        </div>
                        <div>
                            <label className="block text-xs font-bold text-gray-500 mb-1">獎勵說明</label>
                            <input className="border p-2 rounded w-full" value={formData.balloonDesc || ''} onChange={e => handleChange('balloonDesc', e.target.value)} placeholder="例如：結帳現折 $500" />
                        </div>
                    </div>
                    <p className="text-xs text-gray-400">開啟後，前台會隨機飄出氣球，擊落後顯示此優惠碼。</p>
                </div>
            </div>

            {/* Images (Simple Inputs for now) */}
            <div>
                <h3 className="font-bold mb-4 text-lg text-ac-darkBrown border-b pb-2">圖片設定</h3>
                <div className="space-y-4">
                    <div><label className="block text-xs font-bold text-gray-500">Hero Image URL (Base64/Link)</label><input className="border p-2 rounded w-full text-xs" value={formData.heroImage || ''} onChange={e => handleChange('heroImage', e.target.value)} /></div>
                    <div><label className="block text-xs font-bold text-gray-500">Story Image 1 URL</label><input className="border p-2 rounded w-full text-xs" value={formData.storyImage1 || ''} onChange={e => handleChange('storyImage1', e.target.value)} /></div>
                    <div><label className="block text-xs font-bold text-gray-500">Story Image 2 URL</label><input className="border p-2 rounded w-full text-xs" value={formData.storyImage2 || ''} onChange={e => handleChange('storyImage2', e.target.value)} /></div>
                </div>
            </div>

            <button onClick={handleSave} className="w-full bg-ac-green text-white py-3 rounded-xl font-bold shadow-md hover:bg-[#66a04b]">儲存所有設定</button>
        </div>
    );
};

const ProductEditor = ({ product, onClose, onSave }: { product: Product | null, onClose: () => void, onSave: (p: Product) => void }) => {
    const [activeTab, setActiveTab] = useState<'basic' | 'details' | 'media' | 'seo'>('basic');
    const [formData, setFormData] = useState<Partial<Product>>(product || {
        id: Date.now().toString(), name: '', category: 'Home', price: 0, description: '', fullDescription: '',
        tags: [], features: [], specs: [], variants: [], imagePrompt: 'Animal Crossing style item', uploadedImage: '', galleryPrompts: [],
        seo: { title: '', description: '', keywords: [] }
    });
    const [isSeoGenerating, setIsSeoGenerating] = useState(false);
    const [isDescGenerating, setIsDescGenerating] = useState(false);
    const [isImageGenerating, setIsImageGenerating] = useState(false);

    // Helpers for complex fields
    const handleAddFeature = () => setFormData({ ...formData, features: [...(formData.features || []), { icon: '✨', label: '新特色' }] });
    const updateFeature = (idx: number, field: 'icon' | 'label', value: string) => {
        const newFeatures = [...(formData.features || [])];
        newFeatures[idx] = { ...newFeatures[idx], [field]: value };
        setFormData({ ...formData, features: newFeatures });
    };
    const removeFeature = (idx: number) => setFormData({ ...formData, features: formData.features?.filter((_, i) => i !== idx) });

    const handleAddSpec = () => setFormData({ ...formData, specs: [...(formData.specs || []), { label: '規格', value: '內容' }] });
    const updateSpec = (idx: number, field: 'label' | 'value', value: string) => {
        const newSpecs = [...(formData.specs || [])];
        newSpecs[idx] = { ...newSpecs[idx], [field]: value };
        setFormData({ ...formData, specs: newSpecs });
    };
    const removeSpec = (idx: number) => setFormData({ ...formData, specs: formData.specs?.filter((_, i) => i !== idx) });

    const handleAddGallery = () => setFormData({ ...formData, galleryPrompts: [...(formData.galleryPrompts || []), ''] });
    const updateGallery = (idx: number, value: string) => {
        const newGallery = [...(formData.galleryPrompts || [])];
        newGallery[idx] = value;
        setFormData({ ...formData, galleryPrompts: newGallery });
    };
    const removeGallery = (idx: number) => setFormData({ ...formData, galleryPrompts: formData.galleryPrompts?.filter((_, i) => i !== idx) });

    const handleAddVariant = () => setFormData({ ...formData, variants: [...(formData.variants || []), { id: Date.now().toString(), name: '', price: 0 }] });
    const updateVariant = (idx: number, field: 'name' | 'price' | 'id', value: string | number) => {
        const newVariants = [...(formData.variants || [])];
        newVariants[idx] = { ...newVariants[idx], [field]: value };
        setFormData({ ...formData, variants: newVariants });
    };
    const removeVariant = (idx: number) => setFormData({ ...formData, variants: formData.variants?.filter((_, i) => i !== idx) });

    const handleGenerateDesc = async () => {
        if (!formData.name) return alert('請先輸入名稱');
        setIsDescGenerating(true);
        const desc = await generateProductDescription(formData.name || '', formData.category || '', formData.tags?.join(',') || '');
        setFormData({ ...formData, fullDescription: desc });
        setIsDescGenerating(false);
    };

    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0]; if(file){const r=new FileReader();r.onload=()=>setFormData({...formData,uploadedImage:r.result as string});r.readAsDataURL(file);}
    };
    const handleGenerateImage = async () => {
        setIsImageGenerating(true); try{const b64=await generateAIImage(formData.imagePrompt!); setFormData({...formData,uploadedImage:b64});}catch(e){}finally{setIsImageGenerating(false);}
    };
    const handleGenerateSEO = async () => {
        setIsSeoGenerating(true); try{const seo=await generateProductSEO(formData); setFormData({...formData,seo});}catch(e){}finally{setIsSeoGenerating(false);}
    };

    return (
        <form onSubmit={e => { e.preventDefault(); onSave(formData as Product); }} className="space-y-6">
            <div className="flex space-x-2 border-b-2 border-ac-cream pb-1 overflow-x-auto">
                {[{id:'basic', label:'基本資訊'}, {id:'details', label:'詳細規格'}, {id:'media', label:'圖片管理'}, {id:'seo', label:'SEO 優化'}].map(tab => (
                    <button type="button" key={tab.id} onClick={() => setActiveTab(tab.id as any)} className={`px-4 py-2 rounded-t-xl font-bold whitespace-nowrap ${activeTab === tab.id ? 'bg-ac-green text-white' : 'text-ac-brown hover:bg-ac-cream'}`}>{tab.label}</button>
                ))}
            </div>

            <div className="min-h-[400px]">
                {activeTab === 'basic' && (
                    <div className="space-y-4 animate-fade-in-up">
                        <div className="grid grid-cols-2 gap-4">
                            <div><label className="block text-xs font-bold text-ac-green mb-1">名稱</label><input required className="border p-2 rounded w-full" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} /></div>
                            <div><label className="block text-xs font-bold text-ac-green mb-1">價格 (顯示用)</label><input required type="number" className="border p-2 rounded w-full" value={formData.price} onChange={e => setFormData({...formData, price: Number(e.target.value)})} /></div>
                        </div>
                        <div><label className="block text-xs font-bold text-ac-green mb-1">分類</label><select className="border p-2 rounded w-full" value={formData.category} onChange={e => setFormData({...formData, category: e.target.value as any})}><option value="Limited">限定</option><option value="Pillow">枕頭</option><option value="Home">居家</option><option value="Accessory">配件</option></select></div>
                        <div><label className="block text-xs font-bold text-ac-green mb-1">簡述</label><textarea className="border p-2 rounded w-full h-16" value={formData.description} onChange={e => setFormData({...formData, description: e.target.value})} /></div>
                        <div>
                            <div className="flex justify-between items-center mb-1"><label className="text-xs font-bold text-ac-green">完整描述</label><button type="button" onClick={handleGenerateDesc} disabled={isDescGenerating} className="text-xs bg-ac-blue text-white px-2 py-1 rounded flex items-center">{isDescGenerating ? '撰寫中...' : <><Icons.Sparkles className="w-3 h-3 mr-1"/> AI 撰寫</>}</button></div>
                            <textarea className="border p-2 rounded w-full h-32" value={formData.fullDescription} onChange={e => setFormData({...formData, fullDescription: e.target.value})} />
                        </div>
                    </div>
                )}

                {activeTab === 'details' && (
                    <div className="space-y-6 animate-fade-in-up">
                         {/* Variants */}
                         <div>
                            <div className="flex justify-between mb-2"><label className="font-bold text-ac-brown">規格變體 (Variants)</label><button type="button" onClick={handleAddVariant} className="text-xs bg-ac-green text-white px-2 py-1 rounded">新增規格</button></div>
                            <div className="space-y-2">
                                {formData.variants?.map((v, i) => (
                                    <div key={i} className="flex gap-2 items-center border p-2 rounded">
                                        <div className="flex-1 grid grid-cols-3 gap-2">
                                            <input className="border rounded px-2 py-1 text-sm" value={v.id} onChange={e => updateVariant(i, 'id', e.target.value)} placeholder="ID (如: double)" />
                                            <input className="border rounded px-2 py-1 text-sm" value={v.name} onChange={e => updateVariant(i, 'name', e.target.value)} placeholder="名稱 (如: 5尺)" />
                                            <input className="border rounded px-2 py-1 text-sm" type="number" value={v.price} onChange={e => updateVariant(i, 'price', Number(e.target.value))} placeholder="價格" />
                                        </div>
                                        <button type="button" onClick={() => removeVariant(i)} className="text-red-400 p-1 hover:bg-red-50 rounded"><Icons.Trash className="w-4 h-4"/></button>
                                    </div>
                                ))}
                                {(!formData.variants || formData.variants.length === 0) && <p className="text-xs text-gray-400">無變體，將使用基本價格。</p>}
                            </div>
                        </div>

                        <div>
                            <div className="flex justify-between mb-2"><label className="font-bold text-ac-brown">商品特色 (Features)</label><button type="button" onClick={handleAddFeature} className="text-xs bg-ac-green text-white px-2 py-1 rounded">新增特色</button></div>
                            <div className="grid grid-cols-2 gap-2">
                                {formData.features?.map((feat, i) => (
                                    <div key={i} className="flex gap-2 items-center border p-2 rounded">
                                        <input className="w-8 text-center border rounded" value={feat.icon} onChange={e => updateFeature(i, 'icon', e.target.value)} placeholder="Icon" />
                                        <input className="flex-1 border rounded px-1" value={feat.label} onChange={e => updateFeature(i, 'label', e.target.value)} placeholder="標題" />
                                        <button type="button" onClick={() => removeFeature(i)} className="text-red-400">×</button>
                                    </div>
                                ))}
                            </div>
                        </div>
                        <div>
                            <div className="flex justify-between mb-2"><label className="font-bold text-ac-brown">商品規格 (Specs)</label><button type="button" onClick={handleAddSpec} className="text-xs bg-ac-green text-white px-2 py-1 rounded">新增規格</button></div>
                            <div className="space-y-2">
                                {formData.specs?.map((spec, i) => (
                                    <div key={i} className="flex gap-2 items-center border p-2 rounded">
                                        <input className="w-1/3 border rounded px-1" value={spec.label} onChange={e => updateSpec(i, 'label', e.target.value)} placeholder="項目 (如: 尺寸)" />
                                        <input className="flex-1 border rounded px-1" value={spec.value} onChange={e => updateSpec(i, 'value', e.target.value)} placeholder="內容 (如: 30cm)" />
                                        <button type="button" onClick={() => removeSpec(i)} className="text-red-400">×</button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'media' && (
                    <div className="space-y-4 animate-fade-in-up">
                        <div className="grid grid-cols-2 gap-4">
                            <div><label className="text-xs font-bold text-ac-green">主圖預覽</label><div className="aspect-[4/3] bg-gray-100 rounded border overflow-hidden"><AIImage src={formData.uploadedImage} prompt={formData.imagePrompt} alt="Main" className="w-full h-full object-cover"/></div></div>
                            <div className="flex flex-col gap-2">
                                <label className="text-xs font-bold text-ac-green">AI 生成主圖</label>
                                <textarea className="border p-2 rounded h-20 text-xs" value={formData.imagePrompt} onChange={e => setFormData({...formData, imagePrompt: e.target.value})} placeholder="Prompt..." />
                                <button type="button" onClick={handleGenerateImage} disabled={isImageGenerating} className="bg-ac-blue text-white py-2 rounded text-xs font-bold">{isImageGenerating ? '生成中...' : '生成主圖'}</button>
                                <label className="text-xs font-bold text-ac-green mt-2">或上傳圖片</label>
                                <input type="file" onChange={handleImageUpload} className="text-xs" />
                            </div>
                        </div>
                        <div>
                            <div className="flex justify-between mb-2"><label className="font-bold text-ac-brown">圖庫 Prompts (Gallery)</label><button type="button" onClick={handleAddGallery} className="text-xs bg-ac-green text-white px-2 py-1 rounded">新增圖片 Prompt</button></div>
                            <div className="space-y-2">
                                {formData.galleryPrompts?.map((prompt, i) => (
                                    <div key={i} className="flex gap-2 items-center">
                                        <span className="text-xs text-gray-400">#{i+1}</span>
                                        <input className="flex-1 border p-2 rounded text-sm" value={prompt} onChange={e => updateGallery(i, e.target.value)} placeholder="輸入 Prompt 用於生成附圖..." />
                                        <button type="button" onClick={() => removeGallery(i)} className="text-red-400">×</button>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'seo' && (
                     <div className="space-y-4 animate-fade-in-up">
                        <button type="button" onClick={handleGenerateSEO} disabled={isSeoGenerating} className="w-full bg-ac-orange text-white py-2 rounded font-bold shadow-md">{isSeoGenerating ? '分析中...' : '一鍵生成 SEO 資訊'}</button>
                        <div><label className="text-xs font-bold">Title</label><input className="border p-2 rounded w-full" value={formData.seo?.title} onChange={e => setFormData({...formData, seo:{...formData.seo!, title: e.target.value}})} /></div>
                        <div><label className="text-xs font-bold">Description</label><textarea className="border p-2 rounded w-full h-20" value={formData.seo?.description} onChange={e => setFormData({...formData, seo:{...formData.seo!, description: e.target.value}})} /></div>
                        <div><label className="text-xs font-bold">Keywords (逗號分隔)</label><input className="border p-2 rounded w-full" value={formData.seo?.keywords?.join(',')} onChange={e => setFormData({...formData, seo:{...formData.seo!, keywords: e.target.value.split(',')}})} /></div>
                     </div>
                )}
            </div>
            <div className="flex justify-end gap-2 border-t pt-4"><button type="button" onClick={onClose} className="px-4 py-2 text-gray-500">取消</button><button type="submit" className="bg-ac-green text-white px-6 py-2 rounded font-bold">儲存商品</button></div>
        </form>
    );
};

const BlogEditor = ({ post, onClose, onSave }: { post: BlogPost | null, onClose: () => void, onSave: (p: BlogPost) => void }) => {
    const [formData, setFormData] = useState<Partial<BlogPost>>(post || {
        id: Date.now().toString(), title: '', category: '日記', date: new Date().toISOString().split('T')[0],
        content: '', excerpt: '', author: '哈姆店長', tags: [], imagePrompt: 'Animal Crossing style scene'
    });
    const [isGeneratingImage, setIsGeneratingImage] = useState(false);
    
    // Tag handlers
    const handleTagsChange = (val: string) => setFormData({ ...formData, tags: val.split(',').map(s => s.trim()).filter(s => s) });
    const handleGenerateImage = async () => { setIsGeneratingImage(true); try{const b64=await generateAIImage(formData.imagePrompt!); const win=window.open(); if(win){win.document.write(`<img src="${b64}"/>`);}}catch(e){}finally{setIsGeneratingImage(false);} };

    return (
        <form onSubmit={e => { e.preventDefault(); onSave(formData as BlogPost); }} className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
                <input required placeholder="標題" className="border p-2 rounded" value={formData.title} onChange={e => setFormData({...formData, title: e.target.value})} />
                <input required placeholder="日期" className="border p-2 rounded" value={formData.date} onChange={e => setFormData({...formData, date: e.target.value})} />
            </div>
             <div className="grid grid-cols-2 gap-4">
                <input required placeholder="分類" className="border p-2 rounded" value={formData.category} onChange={e => setFormData({...formData, category: e.target.value})} />
                <input required placeholder="作者" className="border p-2 rounded" value={formData.author} onChange={e => setFormData({...formData, author: e.target.value})} />
            </div>
            <textarea required placeholder="摘要" className="border p-2 rounded w-full h-16" value={formData.excerpt} onChange={e => setFormData({...formData, excerpt: e.target.value})} />
            <textarea required placeholder="內容 (HTML)" className="border p-2 rounded w-full h-48 font-mono text-sm" value={formData.content} onChange={e => setFormData({...formData, content: e.target.value})} />
            
            <div>
                <label className="text-xs font-bold text-ac-green">標籤 (Tags) - 以逗號分隔</label>
                <input placeholder="例如: 睡眠, 健康, 推薦" className="border p-2 rounded w-full" value={formData.tags?.join(', ')} onChange={e => handleTagsChange(e.target.value)} />
            </div>

            <div className="flex gap-2 items-center bg-gray-50 p-2 rounded">
                <input placeholder="圖片 Prompt" className="border p-2 rounded flex-1" value={formData.imagePrompt} onChange={e => setFormData({...formData, imagePrompt: e.target.value})} />
                <button type="button" onClick={handleGenerateImage} disabled={isGeneratingImage} className="bg-ac-blue text-white px-3 py-2 rounded text-xs font-bold whitespace-nowrap">{isGeneratingImage ? '...' : '生成預覽'}</button>
            </div>
            
            <div className="flex justify-end gap-2 mt-4"><button type="button" onClick={onClose} className="px-4 py-2 text-gray-500">取消</button><button type="submit" className="bg-ac-blue text-white px-6 py-2 rounded font-bold">發佈</button></div>
        </form>
    );
};

const ProductsTab = ({ products, refresh }: { products: Product[], refresh: () => void }) => {
    const [editingProduct, setEditingProduct] = useState<Product | null>(null);
    const [isCreating, setIsCreating] = useState(false);
    const handleSave = async (p: Product) => { await dataService.saveProduct(p); refresh(); setEditingProduct(null); setIsCreating(false); };
    const handleDelete = async (id: string) => { if (confirm('Del?')) { await dataService.deleteProduct(id); refresh(); } };

    if (editingProduct || isCreating) return <div className="bg-white rounded-2xl shadow-sm p-6"><h3 className="text-xl font-bold mb-6">{isCreating?'新增':'編輯'}商品</h3><ProductEditor product={editingProduct} onClose={() => {setEditingProduct(null); setIsCreating(false);}} onSave={handleSave} /></div>;

    return (
        <div className="bg-white rounded-2xl shadow-sm p-6">
            <div className="flex justify-between items-center mb-6"><h3 className="text-xl font-bold">商品列表</h3><button onClick={() => setIsCreating(true)} className="bg-ac-green text-white px-3 py-2 rounded font-bold shadow-md">新增商品</button></div>
            <div className="space-y-4">{products.map(p => <div key={p.id} className="border p-4 rounded flex gap-4 items-center"><div className="w-12 h-12 bg-gray-200 rounded overflow-hidden"><AIImage src={p.uploadedImage} prompt={p.imagePrompt} alt={p.name} className="w-full h-full object-cover"/></div><div className="flex-1 font-bold"><div>{p.name}</div><div className="text-xs text-gray-500">{p.variants?.length ? `[${p.variants.length} 規格]` : '單一規格'}</div></div><button onClick={() => setEditingProduct(p)} className="text-blue-500"><Icons.Edit className="w-5 h-5"/></button><button onClick={() => handleDelete(p.id)} className="text-red-400"><Icons.Trash className="w-5 h-5"/></button></div>)}</div>
        </div>
    );
};

const BlogTab = ({ posts, refresh, settings }: { posts: BlogPost[], refresh: () => void, settings: SiteSettings }) => {
    const [editingPost, setEditingPost] = useState<BlogPost | null>(null);
    const [isCreating, setIsCreating] = useState(false);
    const [isGenerating, setIsGenerating] = useState(false);

    // Auto-generate check
    useEffect(() => {
        const checkSchedule = async () => {
            if (settings.blogAutoGenerateInterval && settings.blogAutoGenerateInterval !== 'off') {
                const lastGen = settings.lastBlogAutoGenerateDate ? new Date(settings.lastBlogAutoGenerateDate) : new Date(0);
                const diffHours = (new Date().getTime() - lastGen.getTime()) / (1000 * 60 * 60);
                if ((settings.blogAutoGenerateInterval === 'daily' && diffHours >= 24) || (settings.blogAutoGenerateInterval === 'weekly' && diffHours >= 168)) {
                    try { const newPost = await generateAIBlogPost(); await dataService.saveBlogPost(newPost); await dataService.saveSiteSettings({ ...settings, lastBlogAutoGenerateDate: new Date().toISOString() }); refresh(); } catch (e) {}
                }
            }
        }; checkSchedule();
    }, [settings, refresh]);

    const handleSave = async (p: BlogPost) => { await dataService.saveBlogPost(p); refresh(); setEditingPost(null); setIsCreating(false); };
    const handleDelete = async (id: string) => { if (confirm('Del?')) { await dataService.deleteBlogPost(id); refresh(); } };
    const handleAiGenerate = async () => { setIsGenerating(true); try{const p=await generateAIBlogPost(); await dataService.saveBlogPost(p); refresh(); alert('OK');}catch(e){alert('Fail');}finally{setIsGenerating(false);} };
    const handleScheduleChange = async (v: string) => { await dataService.saveSiteSettings({ ...settings, blogAutoGenerateInterval: v as any }); refresh(); };

    if (editingPost || isCreating) return <div className="bg-white rounded-2xl shadow-sm p-6"><h3 className="text-xl font-bold mb-6">{isCreating?'新增':'編輯'}日記</h3><BlogEditor post={editingPost} onClose={() => {setEditingPost(null); setIsCreating(false);}} onSave={handleSave} /></div>;

    return (
        <div className="bg-white rounded-2xl shadow-sm p-6">
            <div className="flex justify-between items-center mb-6 flex-wrap gap-4">
                <h3 className="text-xl font-bold">日記列表</h3>
                <div className="flex gap-2 items-center"><span className="text-xs font-bold text-gray-500">自動:</span><select value={settings.blogAutoGenerateInterval||'off'} onChange={e=>handleScheduleChange(e.target.value)} className="text-xs font-bold bg-gray-100 rounded p-1"><option value="off">關閉</option><option value="daily">每日</option><option value="weekly">每週</option></select></div>
                <div className="flex gap-2"><button onClick={handleAiGenerate} disabled={isGenerating} className="bg-ac-blue text-white px-3 py-2 rounded font-bold text-sm shadow-md">{isGenerating?'...':'AI 靈感撰寫'}</button><button onClick={() => setIsCreating(true)} className="bg-ac-green text-white px-3 py-2 rounded font-bold text-sm shadow-md">新增</button></div>
            </div>
            <div className="space-y-4">{posts.map(p => <div key={p.id} className="border p-4 rounded flex gap-4 items-center"><div className="w-12 h-12 bg-gray-200 rounded overflow-hidden"><AIImage prompt={p.imagePrompt} alt={p.title} className="w-full h-full object-cover"/></div><div className="flex-1 font-bold">{p.title}</div><button onClick={() => setEditingPost(p)} className="text-blue-500"><Icons.Edit className="w-5 h-5"/></button><button onClick={() => handleDelete(p.id)} className="text-red-400"><Icons.Trash className="w-5 h-5"/></button></div>)}</div>
        </div>
    );
};
